export const initialValues = {
  nombre: "",
  apellidos: "",
  provincia: "",
  municipio: "",
  direccion: "",
  numeroCasa: "",
  telefonoFijo: "",
  telefonoCelular: "",
  carneIdentidad: "",
  guardarDestinatario: false,
  nombreEnvio: "",
  apellidosEnvio: "",
  direccionEnvio: "",
  telefonoEnvio: "",
  direccionFacturacionIgual: false,
  productos: [],
};
